package game;

enum CardEffect{
	ADD_CURSE_OTHER;
	REMOVE_CURSE_OTHER;
	ADD_CURSE_SELF;
	REMOVE_CURSE_SELF;
	TAKE_CURSE;
	GIVE_CURSE;
	GAIN_POINT;
	REMOVE_POINT;
	SEAL_OWN_CURSE;
	SEAL_OTHER_CURSE;
	PROTECT_SELF;
	PROTECT_OTHER;
}